export const response = {
    towers: [
        { value: "А", available: true },
        { value: "Б", available: true },
    ],
    floors: [
        { value: 3, available: true },
        { value: 4, available: true },
        { value: 5, available: true },
        { value: 6, available: true },
        { value: 7, available: true },
        { value: 8, available: true },
        { value: 9, available: true },
        { value: 10, available: true },
        { value: 11, available: true },
        { value: 12, available: true },
        { value: 13, available: true },
        { value: 14, available: true },
        { value: 15, available: true },
        { value: 16, available: true },
        { value: 17, available: true },
        { value: 18, available: true },
        { value: 19, available: true },
        { value: 20, available: true },
        { value: 21, available: true },
        { value: 22, available: true },
        { value: 23, available: true },
        { value: 24, available: true },
        { value: 25, available: true },
        { value: 26, available: true },
        { value: 27, available: true },
    ],
    rooms: [
        { value: 1, available: true },
        { value: 2, available: true },
        { value: 3, available: true },
        { value: 4, available: true },
        { value: 5, available: true },
        { value: 6, available: true },
        { value: 7, available: true },
        { value: 8, available: true },
        { value: 9, available: true },
        { value: 10, available: true },
    ],
    booked: [
        { tower: 'А', floor: '3', room: '1', dateStart: "2023-05-09T09:30:00.000Z", dateEnd: "2023-05-09T10:30:00.000Z" },
        { tower: 'Б', floor: '3', room: '1', dateStart: "2023-05-09T09:30:00.000Z", dateEnd: "2023-05-09T10:30:00.000Z" },
    ]
};
